site_name: MkDocs
site_url: http://www.mkdocs.org/
site_description: Project documentation with Markdown.

repo_url: https://github.com/tomchristie/mkdocs/

pages:
- Home: index.md
- User Guide:
  - Configuration: user-guide/configuration.md
  - Writing your docs: user-guide/writing-your-docs.md
  - Styling your docs: user-guide/styling-your-docs.md
- About:
  - License: about/license.md
  - Release Notes: about/release-notes.md

copyright: Copyright &copy; 2014, <a href="https://twitter.com/_tomchristie">Tom Christie</a>.
google_analytics: ['UA-27795084-5', 'mkdocs.org']
